// Generated from bian-services/registry.json — do not hand-edit.
// Regenerate: python3 ../scripts/… (see docs-site notes in README)
const GH_OWNER = 'Sreenivas-Sadhu-Prabhakara';
const REGISTRY = [
 {
  "repo": "sd-party-reference-data-directory",
  "serviceDomain": "Party Reference Data Directory",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Catalog",
  "assetType": "Party Reference Data",
  "controlRecord": "Party Reference Data Directory Entry",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.partyreferencedatadirectory",
  "deep": false
 },
 {
  "repo": "sd-customer-reference-data-management",
  "serviceDomain": "Customer Reference Data Management",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Maintain",
  "assetType": "Customer Reference Data",
  "controlRecord": "Customer Reference Data Maintenance Agreement",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.customerreferencedatamanagement",
  "deep": false
 },
 {
  "repo": "sd-product-directory",
  "serviceDomain": "Product Directory",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Catalog",
  "assetType": "Product Reference Data",
  "controlRecord": "Product Reference Data Directory Entry",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.productdirectory",
  "deep": false
 },
 {
  "repo": "sd-location-data-management",
  "serviceDomain": "Location Data Management",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Maintain",
  "assetType": "Location Reference Data",
  "controlRecord": "Location Reference Data Maintenance Agreement",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.locationdatamanagement",
  "deep": false
 },
 {
  "repo": "sd-financial-market-reference-data",
  "serviceDomain": "Financial Market Reference Data",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Catalog",
  "assetType": "Market Reference Data",
  "controlRecord": "Market Reference Data Directory Entry",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.financialmarketreferencedata",
  "deep": false
 },
 {
  "repo": "sd-market-data-switch-operation",
  "serviceDomain": "Market Data Switch Operation",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Operate",
  "assetType": "Market Data Feed",
  "controlRecord": "Market Data Feed Operating Session",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.marketdataswitchoperation",
  "deep": false
 },
 {
  "repo": "sd-information-provider-operation",
  "serviceDomain": "Information Provider Operation",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Operate",
  "assetType": "Information Feed",
  "controlRecord": "Information Feed Operating Session",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.informationprovideroperation",
  "deep": false
 },
 {
  "repo": "sd-quoted-securities-service",
  "serviceDomain": "Quoted Securities Service",
  "businessArea": "Reference Data",
  "businessDomain": "Reference Data",
  "functionalPattern": "Catalog",
  "assetType": "Securities Reference Data",
  "controlRecord": "Securities Reference Data Directory Entry",
  "namespace": "bian-reference-data",
  "package": "com.bank.bian.quotedsecuritiesservice",
  "deep": false
 },
 {
  "repo": "sd-customer-relationship-management",
  "serviceDomain": "Customer Relationship Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Direct",
  "assetType": "Customer Relationship",
  "controlRecord": "Customer Relationship Strategy",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customerrelationshipmanagement",
  "deep": false
 },
 {
  "repo": "sd-customer-profile",
  "serviceDomain": "Customer Profile",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Maintain",
  "assetType": "Customer Profile",
  "controlRecord": "Customer Profile Maintenance Agreement",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customerprofile",
  "deep": false
 },
 {
  "repo": "sd-customer-agreement",
  "serviceDomain": "Customer Agreement",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Manage",
  "assetType": "Customer Agreement",
  "controlRecord": "Customer Agreement Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customeragreement",
  "deep": false
 },
 {
  "repo": "sd-customer-behavior-insights",
  "serviceDomain": "Customer Behavior Insights",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Analyze",
  "assetType": "Customer Behavior Model",
  "controlRecord": "Customer Behavior Model Analysis",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customerbehaviorinsights",
  "deep": false
 },
 {
  "repo": "sd-customer-event-history",
  "serviceDomain": "Customer Event History",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Maintain",
  "assetType": "Customer Event Log",
  "controlRecord": "Customer Event Log Maintenance Agreement",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customereventhistory",
  "deep": false
 },
 {
  "repo": "sd-customer-case-management",
  "serviceDomain": "Customer Case Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Manage",
  "assetType": "Customer Case",
  "controlRecord": "Customer Case Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customercasemanagement",
  "deep": false
 },
 {
  "repo": "sd-customer-access-entitlement",
  "serviceDomain": "Customer Access Entitlement",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Administer",
  "assetType": "Access Entitlement",
  "controlRecord": "Access Entitlement Administrative Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customeraccessentitlement",
  "deep": false
 },
 {
  "repo": "sd-customer-position",
  "serviceDomain": "Customer Position",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Manage",
  "assetType": "Customer Position",
  "controlRecord": "Customer Position Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customerposition",
  "deep": false
 },
 {
  "repo": "sd-party-lifecycle-management",
  "serviceDomain": "Party Lifecycle Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Manage",
  "assetType": "Party Record",
  "controlRecord": "Party Record Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.partylifecyclemanagement",
  "deep": false
 },
 {
  "repo": "sd-customer-tax-handling",
  "serviceDomain": "Customer Tax Handling",
  "businessArea": "Sales and Service",
  "businessDomain": "Customer Management",
  "functionalPattern": "Process",
  "assetType": "Customer Tax Record",
  "controlRecord": "Customer Tax Record Procedure",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customertaxhandling",
  "deep": false
 },
 {
  "repo": "sd-sales-planning",
  "serviceDomain": "Sales Planning",
  "businessArea": "Sales and Service",
  "businessDomain": "Sales",
  "functionalPattern": "Plan",
  "assetType": "Sales Plan",
  "controlRecord": "Sales Plan Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.salesplanning",
  "deep": false
 },
 {
  "repo": "sd-lead-opportunity-management",
  "serviceDomain": "Lead Opportunity Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Sales",
  "functionalPattern": "Manage",
  "assetType": "Sales Lead",
  "controlRecord": "Sales Lead Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.leadopportunitymanagement",
  "deep": false
 },
 {
  "repo": "sd-customer-offer",
  "serviceDomain": "Customer Offer",
  "businessArea": "Sales and Service",
  "businessDomain": "Sales",
  "functionalPattern": "Manage",
  "assetType": "Customer Offer",
  "controlRecord": "Customer Offer Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customeroffer",
  "deep": false
 },
 {
  "repo": "sd-product-matching",
  "serviceDomain": "Product Matching",
  "businessArea": "Sales and Service",
  "businessDomain": "Sales",
  "functionalPattern": "Process",
  "assetType": "Product Match",
  "controlRecord": "Product Match Procedure",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.productmatching",
  "deep": false
 },
 {
  "repo": "sd-sales-product-agreement",
  "serviceDomain": "Sales Product Agreement",
  "businessArea": "Sales and Service",
  "businessDomain": "Sales",
  "functionalPattern": "Manage",
  "assetType": "Sales Product Agreement",
  "controlRecord": "Sales Product Agreement Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.salesproductagreement",
  "deep": false
 },
 {
  "repo": "sd-prospect-campaign-design",
  "serviceDomain": "Prospect Campaign Design",
  "businessArea": "Sales and Service",
  "businessDomain": "Sales",
  "functionalPattern": "Design",
  "assetType": "Prospect Campaign",
  "controlRecord": "Prospect Campaign Design",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.prospectcampaigndesign",
  "deep": false
 },
 {
  "repo": "sd-brand-management",
  "serviceDomain": "Brand Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Marketing",
  "functionalPattern": "Manage",
  "assetType": "Brand Plan",
  "controlRecord": "Brand Plan Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.brandmanagement",
  "deep": false
 },
 {
  "repo": "sd-advertising",
  "serviceDomain": "Advertising",
  "businessArea": "Sales and Service",
  "businessDomain": "Marketing",
  "functionalPattern": "Operate",
  "assetType": "Advertising Campaign",
  "controlRecord": "Advertising Campaign Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.advertising",
  "deep": false
 },
 {
  "repo": "sd-marketing-campaign-design",
  "serviceDomain": "Marketing Campaign Design",
  "businessArea": "Sales and Service",
  "businessDomain": "Marketing",
  "functionalPattern": "Design",
  "assetType": "Marketing Campaign",
  "controlRecord": "Marketing Campaign Design",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.marketingcampaigndesign",
  "deep": false
 },
 {
  "repo": "sd-promotional-events",
  "serviceDomain": "Promotional Events",
  "businessArea": "Sales and Service",
  "businessDomain": "Marketing",
  "functionalPattern": "Operate",
  "assetType": "Promotional Event",
  "controlRecord": "Promotional Event Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.promotionalevents",
  "deep": false
 },
 {
  "repo": "sd-market-research",
  "serviceDomain": "Market Research",
  "businessArea": "Sales and Service",
  "businessDomain": "Marketing",
  "functionalPattern": "Analyze",
  "assetType": "Market Research Study",
  "controlRecord": "Market Research Study Analysis",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.marketresearch",
  "deep": false
 },
 {
  "repo": "sd-customer-surveys",
  "serviceDomain": "Customer Surveys",
  "businessArea": "Sales and Service",
  "businessDomain": "Marketing",
  "functionalPattern": "Operate",
  "assetType": "Customer Survey",
  "controlRecord": "Customer Survey Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customersurveys",
  "deep": false
 },
 {
  "repo": "sd-contact-center-operation",
  "serviceDomain": "Contact Center Operation",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Operate",
  "assetType": "Contact Center Session",
  "controlRecord": "Contact Center Session Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.contactcenteroperation",
  "deep": false
 },
 {
  "repo": "sd-contact-center-management",
  "serviceDomain": "Contact Center Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Manage",
  "assetType": "Contact Center Plan",
  "controlRecord": "Contact Center Plan Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.contactcentermanagement",
  "deep": false
 },
 {
  "repo": "sd-contact-routing",
  "serviceDomain": "Contact Routing",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Process",
  "assetType": "Contact Routing Record",
  "controlRecord": "Contact Routing Record Procedure",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.contactrouting",
  "deep": false
 },
 {
  "repo": "sd-branch-location-management",
  "serviceDomain": "Branch Location Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Operate",
  "assetType": "Branch Operation",
  "controlRecord": "Branch Operation Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.branchlocationmanagement",
  "deep": false
 },
 {
  "repo": "sd-e-branch-operation",
  "serviceDomain": "E-Branch Operation",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Operate",
  "assetType": "Digital Branch Session",
  "controlRecord": "Digital Branch Session Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.ebranchoperation",
  "deep": false
 },
 {
  "repo": "sd-atm-network-management",
  "serviceDomain": "ATM Network Management",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Operate",
  "assetType": "ATM Network",
  "controlRecord": "ATM Network Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.atmnetworkmanagement",
  "deep": false
 },
 {
  "repo": "sd-point-of-service",
  "serviceDomain": "Point Of Service",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Operate",
  "assetType": "POS Session",
  "controlRecord": "POS Session Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.pointofservice",
  "deep": false
 },
 {
  "repo": "sd-card-terminal-administration",
  "serviceDomain": "Card Terminal Administration",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Administer",
  "assetType": "Card Terminal",
  "controlRecord": "Card Terminal Administrative Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.cardterminaladministration",
  "deep": false
 },
 {
  "repo": "sd-servicing-mandate",
  "serviceDomain": "Servicing Mandate",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Manage",
  "assetType": "Servicing Mandate",
  "controlRecord": "Servicing Mandate Management Plan",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.servicingmandate",
  "deep": false
 },
 {
  "repo": "sd-servicing-order",
  "serviceDomain": "Servicing Order",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Process",
  "assetType": "Servicing Order",
  "controlRecord": "Servicing Order Procedure",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.servicingorder",
  "deep": false
 },
 {
  "repo": "sd-customer-workbench",
  "serviceDomain": "Customer Workbench",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Operate",
  "assetType": "Servicing Session",
  "controlRecord": "Servicing Session Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.customerworkbench",
  "deep": false
 },
 {
  "repo": "sd-advisor-workbench",
  "serviceDomain": "Advisor Workbench",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Operate",
  "assetType": "Advisory Session",
  "controlRecord": "Advisory Session Operating Session",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.advisorworkbench",
  "deep": false
 },
 {
  "repo": "sd-channel-activity-analysis",
  "serviceDomain": "Channel Activity Analysis",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Analyze",
  "assetType": "Channel Activity Model",
  "controlRecord": "Channel Activity Model Analysis",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.channelactivityanalysis",
  "deep": false
 },
 {
  "repo": "sd-channel-activity-history",
  "serviceDomain": "Channel Activity History",
  "businessArea": "Sales and Service",
  "businessDomain": "Channels",
  "functionalPattern": "Maintain",
  "assetType": "Channel Activity Log",
  "controlRecord": "Channel Activity Log Maintenance Agreement",
  "namespace": "bian-sales-service",
  "package": "com.bank.bian.channelactivityhistory",
  "deep": false
 },
 {
  "repo": "sd-current-account",
  "serviceDomain": "Current Account",
  "businessArea": "Operations and Execution",
  "businessDomain": "Account Management",
  "functionalPattern": "Fulfill",
  "assetType": "Current Account Facility",
  "controlRecord": "Current Account Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.currentaccount",
  "deep": true
 },
 {
  "repo": "sd-savings-account",
  "serviceDomain": "Savings Account",
  "businessArea": "Operations and Execution",
  "businessDomain": "Account Management",
  "functionalPattern": "Fulfill",
  "assetType": "Savings Account Facility",
  "controlRecord": "Savings Account Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.savingsaccount",
  "deep": true
 },
 {
  "repo": "sd-deposit-account",
  "serviceDomain": "Deposit Account",
  "businessArea": "Operations and Execution",
  "businessDomain": "Account Management",
  "functionalPattern": "Fulfill",
  "assetType": "Deposit Account Facility",
  "controlRecord": "Deposit Account Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.depositaccount",
  "deep": false
 },
 {
  "repo": "sd-customer-billing",
  "serviceDomain": "Customer Billing",
  "businessArea": "Operations and Execution",
  "businessDomain": "Account Management",
  "functionalPattern": "Process",
  "assetType": "Customer Bill",
  "controlRecord": "Customer Bill Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.customerbilling",
  "deep": false
 },
 {
  "repo": "sd-reward-points-account",
  "serviceDomain": "Reward Points Account",
  "businessArea": "Operations and Execution",
  "businessDomain": "Account Management",
  "functionalPattern": "Fulfill",
  "assetType": "Reward Points Facility",
  "controlRecord": "Reward Points Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.rewardpointsaccount",
  "deep": false
 },
 {
  "repo": "sd-customer-tax-withholding",
  "serviceDomain": "Customer Tax Withholding",
  "businessArea": "Operations and Execution",
  "businessDomain": "Account Management",
  "functionalPattern": "Process",
  "assetType": "Tax Withholding Record",
  "controlRecord": "Tax Withholding Record Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.customertaxwithholding",
  "deep": false
 },
 {
  "repo": "sd-payment-order",
  "serviceDomain": "Payment Order",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Process",
  "assetType": "Payment Order",
  "controlRecord": "Payment Order Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.paymentorder",
  "deep": true
 },
 {
  "repo": "sd-payment-execution",
  "serviceDomain": "Payment Execution",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Process",
  "assetType": "Payment Transaction",
  "controlRecord": "Payment Transaction Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.paymentexecution",
  "deep": true
 },
 {
  "repo": "sd-payment-initiation",
  "serviceDomain": "Payment Initiation",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Process",
  "assetType": "Payment Instruction",
  "controlRecord": "Payment Instruction Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.paymentinitiation",
  "deep": false
 },
 {
  "repo": "sd-ach-operations",
  "serviceDomain": "ACH Operations",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Operate",
  "assetType": "ACH Batch",
  "controlRecord": "ACH Batch Operating Session",
  "namespace": "bian-operations",
  "package": "com.bank.bian.achoperations",
  "deep": false
 },
 {
  "repo": "sd-bulk-payments",
  "serviceDomain": "Bulk Payments",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Process",
  "assetType": "Bulk Payment File",
  "controlRecord": "Bulk Payment File Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.bulkpayments",
  "deep": false
 },
 {
  "repo": "sd-direct-debit-mandate",
  "serviceDomain": "Direct Debit Mandate",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Manage",
  "assetType": "Direct Debit Mandate",
  "controlRecord": "Direct Debit Mandate Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.directdebitmandate",
  "deep": false
 },
 {
  "repo": "sd-cross-border-payment",
  "serviceDomain": "Cross Border Payment",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Process",
  "assetType": "Cross Border Payment",
  "controlRecord": "Cross Border Payment Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.crossborderpayment",
  "deep": false
 },
 {
  "repo": "sd-correspondent-bank-management",
  "serviceDomain": "Correspondent Bank Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Manage",
  "assetType": "Correspondent Arrangement",
  "controlRecord": "Correspondent Arrangement Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.correspondentbankmanagement",
  "deep": false
 },
 {
  "repo": "sd-cheque-processing",
  "serviceDomain": "Cheque Processing",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Process",
  "assetType": "Cheque Transaction",
  "controlRecord": "Cheque Transaction Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.chequeprocessing",
  "deep": true
 },
 {
  "repo": "sd-clearing-operations",
  "serviceDomain": "Clearing Operations",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Operate",
  "assetType": "Clearing Cycle",
  "controlRecord": "Clearing Cycle Operating Session",
  "namespace": "bian-operations",
  "package": "com.bank.bian.clearingoperations",
  "deep": false
 },
 {
  "repo": "sd-settlement-operations",
  "serviceDomain": "Settlement Operations",
  "businessArea": "Operations and Execution",
  "businessDomain": "Payments",
  "functionalPattern": "Operate",
  "assetType": "Settlement Instruction",
  "controlRecord": "Settlement Instruction Operating Session",
  "namespace": "bian-operations",
  "package": "com.bank.bian.settlementoperations",
  "deep": false
 },
 {
  "repo": "sd-card-authorization",
  "serviceDomain": "Card Authorization",
  "businessArea": "Operations and Execution",
  "businessDomain": "Cards",
  "functionalPattern": "Process",
  "assetType": "Card Authorization",
  "controlRecord": "Card Authorization Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.cardauthorization",
  "deep": false
 },
 {
  "repo": "sd-card-transaction",
  "serviceDomain": "Card Transaction",
  "businessArea": "Operations and Execution",
  "businessDomain": "Cards",
  "functionalPattern": "Process",
  "assetType": "Card Transaction",
  "controlRecord": "Card Transaction Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.cardtransaction",
  "deep": false
 },
 {
  "repo": "sd-card-collections",
  "serviceDomain": "Card Collections",
  "businessArea": "Operations and Execution",
  "businessDomain": "Cards",
  "functionalPattern": "Process",
  "assetType": "Card Collection Case",
  "controlRecord": "Card Collection Case Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.cardcollections",
  "deep": false
 },
 {
  "repo": "sd-card-capture",
  "serviceDomain": "Card Capture",
  "businessArea": "Operations and Execution",
  "businessDomain": "Cards",
  "functionalPattern": "Process",
  "assetType": "Captured Card",
  "controlRecord": "Captured Card Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.cardcapture",
  "deep": false
 },
 {
  "repo": "sd-issued-device-administration",
  "serviceDomain": "Issued Device Administration",
  "businessArea": "Operations and Execution",
  "businessDomain": "Cards",
  "functionalPattern": "Administer",
  "assetType": "Issued Card",
  "controlRecord": "Issued Card Administrative Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.issueddeviceadministration",
  "deep": false
 },
 {
  "repo": "sd-card-network-participant-services",
  "serviceDomain": "Card Network Participant Services",
  "businessArea": "Operations and Execution",
  "businessDomain": "Cards",
  "functionalPattern": "Operate",
  "assetType": "Card Network Membership",
  "controlRecord": "Card Network Membership Operating Session",
  "namespace": "bian-operations",
  "package": "com.bank.bian.cardnetworkparticipantservices",
  "deep": false
 },
 {
  "repo": "sd-card-clearing",
  "serviceDomain": "Card Clearing",
  "businessArea": "Operations and Execution",
  "businessDomain": "Cards",
  "functionalPattern": "Operate",
  "assetType": "Card Clearing Cycle",
  "controlRecord": "Card Clearing Cycle Operating Session",
  "namespace": "bian-operations",
  "package": "com.bank.bian.cardclearing",
  "deep": false
 },
 {
  "repo": "sd-consumer-loan",
  "serviceDomain": "Consumer Loan",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Consumer Loan Facility",
  "controlRecord": "Consumer Loan Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.consumerloan",
  "deep": false
 },
 {
  "repo": "sd-corporate-loan",
  "serviceDomain": "Corporate Loan",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Corporate Loan Facility",
  "controlRecord": "Corporate Loan Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.corporateloan",
  "deep": false
 },
 {
  "repo": "sd-mortgage-loan",
  "serviceDomain": "Mortgage Loan",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Mortgage Facility",
  "controlRecord": "Mortgage Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.mortgageloan",
  "deep": false
 },
 {
  "repo": "sd-syndicated-loan",
  "serviceDomain": "Syndicated Loan",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Syndicated Loan Facility",
  "controlRecord": "Syndicated Loan Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.syndicatedloan",
  "deep": false
 },
 {
  "repo": "sd-leasing",
  "serviceDomain": "Leasing",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Lease Facility",
  "controlRecord": "Lease Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.leasing",
  "deep": false
 },
 {
  "repo": "sd-loan-disbursement",
  "serviceDomain": "Loan Disbursement",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Process",
  "assetType": "Disbursement Instruction",
  "controlRecord": "Disbursement Instruction Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.loandisbursement",
  "deep": false
 },
 {
  "repo": "sd-collateral-administration",
  "serviceDomain": "Collateral Administration",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Administer",
  "assetType": "Collateral Asset",
  "controlRecord": "Collateral Asset Administrative Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.collateraladministration",
  "deep": false
 },
 {
  "repo": "sd-guarantee",
  "serviceDomain": "Guarantee",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Guarantee Facility",
  "controlRecord": "Guarantee Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.guarantee",
  "deep": false
 },
 {
  "repo": "sd-letter-of-credit",
  "serviceDomain": "Letter Of Credit",
  "businessArea": "Operations and Execution",
  "businessDomain": "Loans and Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Letter Of Credit",
  "controlRecord": "Letter Of Credit Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.letterofcredit",
  "deep": false
 },
 {
  "repo": "sd-trade-finance",
  "serviceDomain": "Trade Finance",
  "businessArea": "Operations and Execution",
  "businessDomain": "Trade Banking",
  "functionalPattern": "Fulfill",
  "assetType": "Trade Finance Facility",
  "controlRecord": "Trade Finance Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.tradefinance",
  "deep": false
 },
 {
  "repo": "sd-documentary-collection",
  "serviceDomain": "Documentary Collection",
  "businessArea": "Operations and Execution",
  "businessDomain": "Trade Banking",
  "functionalPattern": "Process",
  "assetType": "Documentary Collection",
  "controlRecord": "Documentary Collection Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.documentarycollection",
  "deep": false
 },
 {
  "repo": "sd-bank-drafts",
  "serviceDomain": "Bank Drafts",
  "businessArea": "Operations and Execution",
  "businessDomain": "Trade Banking",
  "functionalPattern": "Fulfill",
  "assetType": "Bank Draft",
  "controlRecord": "Bank Draft Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.bankdrafts",
  "deep": false
 },
 {
  "repo": "sd-factoring",
  "serviceDomain": "Factoring",
  "businessArea": "Operations and Execution",
  "businessDomain": "Trade Banking",
  "functionalPattern": "Fulfill",
  "assetType": "Factoring Facility",
  "controlRecord": "Factoring Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.factoring",
  "deep": false
 },
 {
  "repo": "sd-trade-services-customer-directory",
  "serviceDomain": "Trade Services Customer Directory",
  "businessArea": "Operations and Execution",
  "businessDomain": "Trade Banking",
  "functionalPattern": "Catalog",
  "assetType": "Trade Counterparty",
  "controlRecord": "Trade Counterparty Directory Entry",
  "namespace": "bian-operations",
  "package": "com.bank.bian.tradeservicescustomerdirectory",
  "deep": false
 },
 {
  "repo": "sd-securities-position-keeping",
  "serviceDomain": "Securities Position Keeping",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Maintain",
  "assetType": "Securities Position",
  "controlRecord": "Securities Position Maintenance Agreement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.securitiespositionkeeping",
  "deep": false
 },
 {
  "repo": "sd-custody-administration",
  "serviceDomain": "Custody Administration",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Administer",
  "assetType": "Custody Holding",
  "controlRecord": "Custody Holding Administrative Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.custodyadministration",
  "deep": false
 },
 {
  "repo": "sd-corporate-action",
  "serviceDomain": "Corporate Action",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Process",
  "assetType": "Corporate Action Event",
  "controlRecord": "Corporate Action Event Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.corporateaction",
  "deep": false
 },
 {
  "repo": "sd-securities-settlement",
  "serviceDomain": "Securities Settlement",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Process",
  "assetType": "Securities Settlement",
  "controlRecord": "Securities Settlement Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.securitiessettlement",
  "deep": false
 },
 {
  "repo": "sd-securities-lending",
  "serviceDomain": "Securities Lending",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Fulfill",
  "assetType": "Securities Loan",
  "controlRecord": "Securities Loan Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.securitieslending",
  "deep": false
 },
 {
  "repo": "sd-trade-order-management",
  "serviceDomain": "Trade Order Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Manage",
  "assetType": "Trade Order",
  "controlRecord": "Trade Order Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.tradeordermanagement",
  "deep": false
 },
 {
  "repo": "sd-investment-portfolio-management",
  "serviceDomain": "Investment Portfolio Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Manage",
  "assetType": "Investment Portfolio",
  "controlRecord": "Investment Portfolio Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.investmentportfoliomanagement",
  "deep": false
 },
 {
  "repo": "sd-investment-portfolio-analysis",
  "serviceDomain": "Investment Portfolio Analysis",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Analyze",
  "assetType": "Portfolio Analysis",
  "controlRecord": "Portfolio Analysis Analysis",
  "namespace": "bian-operations",
  "package": "com.bank.bian.investmentportfolioanalysis",
  "deep": false
 },
 {
  "repo": "sd-brokered-product",
  "serviceDomain": "Brokered Product",
  "businessArea": "Operations and Execution",
  "businessDomain": "Securities",
  "functionalPattern": "Fulfill",
  "assetType": "Brokered Product Facility",
  "controlRecord": "Brokered Product Facility Fulfillment Arrangement",
  "namespace": "bian-operations",
  "package": "com.bank.bian.brokeredproduct",
  "deep": false
 },
 {
  "repo": "sd-financial-instrument-valuation",
  "serviceDomain": "Financial Instrument Valuation",
  "businessArea": "Operations and Execution",
  "businessDomain": "Markets and Treasury",
  "functionalPattern": "Analyze",
  "assetType": "Instrument Valuation",
  "controlRecord": "Instrument Valuation Analysis",
  "namespace": "bian-operations",
  "package": "com.bank.bian.financialinstrumentvaluation",
  "deep": false
 },
 {
  "repo": "sd-quote-management",
  "serviceDomain": "Quote Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Markets and Treasury",
  "functionalPattern": "Manage",
  "assetType": "Market Quote",
  "controlRecord": "Market Quote Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.quotemanagement",
  "deep": false
 },
 {
  "repo": "sd-trading-book-management",
  "serviceDomain": "Trading Book Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Markets and Treasury",
  "functionalPattern": "Manage",
  "assetType": "Trading Book",
  "controlRecord": "Trading Book Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.tradingbookmanagement",
  "deep": false
 },
 {
  "repo": "sd-position-management",
  "serviceDomain": "Position Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Markets and Treasury",
  "functionalPattern": "Manage",
  "assetType": "Market Position",
  "controlRecord": "Market Position Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.positionmanagement",
  "deep": false
 },
 {
  "repo": "sd-currency-position-management",
  "serviceDomain": "Currency Position Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Markets and Treasury",
  "functionalPattern": "Manage",
  "assetType": "Currency Position",
  "controlRecord": "Currency Position Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.currencypositionmanagement",
  "deep": false
 },
 {
  "repo": "sd-treasury-position-management",
  "serviceDomain": "Treasury Position Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Markets and Treasury",
  "functionalPattern": "Manage",
  "assetType": "Treasury Position",
  "controlRecord": "Treasury Position Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.treasurypositionmanagement",
  "deep": false
 },
 {
  "repo": "sd-asset-securitization",
  "serviceDomain": "Asset Securitization",
  "businessArea": "Operations and Execution",
  "businessDomain": "Markets and Treasury",
  "functionalPattern": "Process",
  "assetType": "Securitization Pool",
  "controlRecord": "Securitization Pool Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.assetsecuritization",
  "deep": false
 },
 {
  "repo": "sd-transaction-engine",
  "serviceDomain": "Transaction Engine",
  "businessArea": "Operations and Execution",
  "businessDomain": "Operations",
  "functionalPattern": "Operate",
  "assetType": "Transaction Ledger",
  "controlRecord": "Transaction Ledger Operating Session",
  "namespace": "bian-operations",
  "package": "com.bank.bian.transactionengine",
  "deep": false
 },
 {
  "repo": "sd-reconciliation",
  "serviceDomain": "Reconciliation",
  "businessArea": "Operations and Execution",
  "businessDomain": "Operations",
  "functionalPattern": "Process",
  "assetType": "Reconciliation Case",
  "controlRecord": "Reconciliation Case Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.reconciliation",
  "deep": false
 },
 {
  "repo": "sd-financial-message-gateway",
  "serviceDomain": "Financial Message Gateway",
  "businessArea": "Operations and Execution",
  "businessDomain": "Operations",
  "functionalPattern": "Operate",
  "assetType": "Financial Message",
  "controlRecord": "Financial Message Operating Session",
  "namespace": "bian-operations",
  "package": "com.bank.bian.financialmessagegateway",
  "deep": false
 },
 {
  "repo": "sd-account-reconciliation",
  "serviceDomain": "Account Reconciliation",
  "businessArea": "Operations and Execution",
  "businessDomain": "Operations",
  "functionalPattern": "Process",
  "assetType": "Account Reconciliation",
  "controlRecord": "Account Reconciliation Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.accountreconciliation",
  "deep": false
 },
 {
  "repo": "sd-currency-exchange",
  "serviceDomain": "Currency Exchange",
  "businessArea": "Operations and Execution",
  "businessDomain": "Operations",
  "functionalPattern": "Process",
  "assetType": "FX Deal",
  "controlRecord": "FX Deal Procedure",
  "namespace": "bian-operations",
  "package": "com.bank.bian.currencyexchange",
  "deep": false
 },
 {
  "repo": "sd-open-item-management",
  "serviceDomain": "Open Item Management",
  "businessArea": "Operations and Execution",
  "businessDomain": "Operations",
  "functionalPattern": "Manage",
  "assetType": "Open Item",
  "controlRecord": "Open Item Management Plan",
  "namespace": "bian-operations",
  "package": "com.bank.bian.openitemmanagement",
  "deep": false
 },
 {
  "repo": "sd-customer-credit-rating",
  "serviceDomain": "Customer Credit Rating",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Credit Risk",
  "functionalPattern": "Assess",
  "assetType": "Credit Rating",
  "controlRecord": "Credit Rating Assessment",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.customercreditrating",
  "deep": false
 },
 {
  "repo": "sd-credit-management",
  "serviceDomain": "Credit Management",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Credit Risk",
  "functionalPattern": "Manage",
  "assetType": "Credit Facility Risk",
  "controlRecord": "Credit Facility Risk Management Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.creditmanagement",
  "deep": false
 },
 {
  "repo": "sd-credit-risk-models",
  "serviceDomain": "Credit Risk Models",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Credit Risk",
  "functionalPattern": "Develop",
  "assetType": "Credit Risk Model",
  "controlRecord": "Credit Risk Model Development Project",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.creditriskmodels",
  "deep": false
 },
 {
  "repo": "sd-collateral-asset-administration",
  "serviceDomain": "Collateral Asset Administration",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Credit Risk",
  "functionalPattern": "Administer",
  "assetType": "Collateral Valuation",
  "controlRecord": "Collateral Valuation Administrative Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.collateralassetadministration",
  "deep": false
 },
 {
  "repo": "sd-limit-and-exposure-management",
  "serviceDomain": "Limit And Exposure Management",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Credit Risk",
  "functionalPattern": "Manage",
  "assetType": "Exposure Limit",
  "controlRecord": "Exposure Limit Management Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.limitandexposuremanagement",
  "deep": false
 },
 {
  "repo": "sd-market-risk-models",
  "serviceDomain": "Market Risk Models",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Market and Operational Risk",
  "functionalPattern": "Develop",
  "assetType": "Market Risk Model",
  "controlRecord": "Market Risk Model Development Project",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.marketriskmodels",
  "deep": false
 },
 {
  "repo": "sd-operational-risk-models",
  "serviceDomain": "Operational Risk Models",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Market and Operational Risk",
  "functionalPattern": "Develop",
  "assetType": "Operational Risk Model",
  "controlRecord": "Operational Risk Model Development Project",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.operationalriskmodels",
  "deep": false
 },
 {
  "repo": "sd-liquidity-risk-models",
  "serviceDomain": "Liquidity Risk Models",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Market and Operational Risk",
  "functionalPattern": "Develop",
  "assetType": "Liquidity Risk Model",
  "controlRecord": "Liquidity Risk Model Development Project",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.liquidityriskmodels",
  "deep": false
 },
 {
  "repo": "sd-liquidity-management",
  "serviceDomain": "Liquidity Management",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Market and Operational Risk",
  "functionalPattern": "Manage",
  "assetType": "Liquidity Position",
  "controlRecord": "Liquidity Position Management Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.liquiditymanagement",
  "deep": false
 },
 {
  "repo": "sd-asset-liability-management",
  "serviceDomain": "Asset Liability Management",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Market and Operational Risk",
  "functionalPattern": "Manage",
  "assetType": "ALM Position",
  "controlRecord": "ALM Position Management Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.assetliabilitymanagement",
  "deep": false
 },
 {
  "repo": "sd-fraud-detection",
  "serviceDomain": "Fraud Detection",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Financial Crime",
  "functionalPattern": "Monitor",
  "assetType": "Fraud Alert",
  "controlRecord": "Fraud Alert Monitoring State",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.frauddetection",
  "deep": true
 },
 {
  "repo": "sd-fraud-diagnosis",
  "serviceDomain": "Fraud Diagnosis",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Financial Crime",
  "functionalPattern": "Assess",
  "assetType": "Fraud Case",
  "controlRecord": "Fraud Case Assessment",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.frauddiagnosis",
  "deep": false
 },
 {
  "repo": "sd-fraud-resolution",
  "serviceDomain": "Fraud Resolution",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Financial Crime",
  "functionalPattern": "Process",
  "assetType": "Fraud Resolution",
  "controlRecord": "Fraud Resolution Procedure",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.fraudresolution",
  "deep": false
 },
 {
  "repo": "sd-financial-crime-models",
  "serviceDomain": "Financial Crime Models",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Financial Crime",
  "functionalPattern": "Develop",
  "assetType": "Financial Crime Model",
  "controlRecord": "Financial Crime Model Development Project",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.financialcrimemodels",
  "deep": false
 },
 {
  "repo": "sd-know-your-customer",
  "serviceDomain": "Know Your Customer",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Financial Crime",
  "functionalPattern": "Process",
  "assetType": "KYC Assessment",
  "controlRecord": "KYC Assessment Procedure",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.knowyourcustomer",
  "deep": true
 },
 {
  "repo": "sd-anti-money-laundering",
  "serviceDomain": "Anti Money Laundering",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Financial Crime",
  "functionalPattern": "Monitor",
  "assetType": "AML Alert",
  "controlRecord": "AML Alert Monitoring State",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.antimoneylaundering",
  "deep": false
 },
 {
  "repo": "sd-case-management-financial-crime",
  "serviceDomain": "Case Management Financial Crime",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Financial Crime",
  "functionalPattern": "Manage",
  "assetType": "Financial Crime Case",
  "controlRecord": "Financial Crime Case Management Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.casemanagementfinancialcrime",
  "deep": false
 },
 {
  "repo": "sd-regulatory-compliance",
  "serviceDomain": "Regulatory Compliance",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Compliance",
  "functionalPattern": "Manage",
  "assetType": "Compliance Requirement",
  "controlRecord": "Compliance Requirement Management Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.regulatorycompliance",
  "deep": false
 },
 {
  "repo": "sd-regulatory-reporting",
  "serviceDomain": "Regulatory Reporting",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Compliance",
  "functionalPattern": "Process",
  "assetType": "Regulatory Report",
  "controlRecord": "Regulatory Report Procedure",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.regulatoryreporting",
  "deep": false
 },
 {
  "repo": "sd-guideline-compliance",
  "serviceDomain": "Guideline Compliance",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Compliance",
  "functionalPattern": "Monitor",
  "assetType": "Compliance Check",
  "controlRecord": "Compliance Check Monitoring State",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.guidelinecompliance",
  "deep": false
 },
 {
  "repo": "sd-information-security",
  "serviceDomain": "Information Security",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Compliance",
  "functionalPattern": "Administer",
  "assetType": "Security Policy",
  "controlRecord": "Security Policy Administrative Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.informationsecurity",
  "deep": false
 },
 {
  "repo": "sd-internal-audit",
  "serviceDomain": "Internal Audit",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Compliance",
  "functionalPattern": "Assess",
  "assetType": "Audit Engagement",
  "controlRecord": "Audit Engagement Assessment",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.internalaudit",
  "deep": false
 },
 {
  "repo": "sd-records-management",
  "serviceDomain": "Records Management",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Compliance",
  "functionalPattern": "Maintain",
  "assetType": "Record Archive",
  "controlRecord": "Record Archive Maintenance Agreement",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.recordsmanagement",
  "deep": false
 },
 {
  "repo": "sd-continuity-planning",
  "serviceDomain": "Continuity Planning",
  "businessArea": "Risk and Compliance",
  "businessDomain": "Compliance",
  "functionalPattern": "Plan",
  "assetType": "Continuity Plan",
  "controlRecord": "Continuity Plan Plan",
  "namespace": "bian-risk-compliance",
  "package": "com.bank.bian.continuityplanning",
  "deep": false
 },
 {
  "repo": "sd-financial-control",
  "serviceDomain": "Financial Control",
  "businessArea": "Business Support",
  "businessDomain": "Finance",
  "functionalPattern": "Manage",
  "assetType": "Financial Control Record",
  "controlRecord": "Financial Control Record Management Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.financialcontrol",
  "deep": false
 },
 {
  "repo": "sd-financial-statements",
  "serviceDomain": "Financial Statements",
  "businessArea": "Business Support",
  "businessDomain": "Finance",
  "functionalPattern": "Process",
  "assetType": "Financial Statement",
  "controlRecord": "Financial Statement Procedure",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.financialstatements",
  "deep": false
 },
 {
  "repo": "sd-management-accounting",
  "serviceDomain": "Management Accounting",
  "businessArea": "Business Support",
  "businessDomain": "Finance",
  "functionalPattern": "Process",
  "assetType": "Management Account",
  "controlRecord": "Management Account Procedure",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.managementaccounting",
  "deep": false
 },
 {
  "repo": "sd-corporate-treasury",
  "serviceDomain": "Corporate Treasury",
  "businessArea": "Business Support",
  "businessDomain": "Finance",
  "functionalPattern": "Manage",
  "assetType": "Treasury Plan",
  "controlRecord": "Treasury Plan Management Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.corporatetreasury",
  "deep": false
 },
 {
  "repo": "sd-capital-management",
  "serviceDomain": "Capital Management",
  "businessArea": "Business Support",
  "businessDomain": "Finance",
  "functionalPattern": "Manage",
  "assetType": "Capital Plan",
  "controlRecord": "Capital Plan Management Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.capitalmanagement",
  "deep": false
 },
 {
  "repo": "sd-tax-management",
  "serviceDomain": "Tax Management",
  "businessArea": "Business Support",
  "businessDomain": "Finance",
  "functionalPattern": "Process",
  "assetType": "Corporate Tax Record",
  "controlRecord": "Corporate Tax Record Procedure",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.taxmanagement",
  "deep": false
 },
 {
  "repo": "sd-employee-data-management",
  "serviceDomain": "Employee Data Management",
  "businessArea": "Business Support",
  "businessDomain": "Human Resources",
  "functionalPattern": "Maintain",
  "assetType": "Employee Record",
  "controlRecord": "Employee Record Maintenance Agreement",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.employeedatamanagement",
  "deep": false
 },
 {
  "repo": "sd-employee-assignment",
  "serviceDomain": "Employee Assignment",
  "businessArea": "Business Support",
  "businessDomain": "Human Resources",
  "functionalPattern": "Manage",
  "assetType": "Employee Assignment",
  "controlRecord": "Employee Assignment Management Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.employeeassignment",
  "deep": false
 },
 {
  "repo": "sd-workforce-training",
  "serviceDomain": "Workforce Training",
  "businessArea": "Business Support",
  "businessDomain": "Human Resources",
  "functionalPattern": "Operate",
  "assetType": "Training Program",
  "controlRecord": "Training Program Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.workforcetraining",
  "deep": false
 },
 {
  "repo": "sd-employee-certification",
  "serviceDomain": "Employee Certification",
  "businessArea": "Business Support",
  "businessDomain": "Human Resources",
  "functionalPattern": "Administer",
  "assetType": "Certification Record",
  "controlRecord": "Certification Record Administrative Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.employeecertification",
  "deep": false
 },
 {
  "repo": "sd-employee-payroll",
  "serviceDomain": "Employee Payroll",
  "businessArea": "Business Support",
  "businessDomain": "Human Resources",
  "functionalPattern": "Process",
  "assetType": "Payroll Run",
  "controlRecord": "Payroll Run Procedure",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.employeepayroll",
  "deep": false
 },
 {
  "repo": "sd-employee-benefits",
  "serviceDomain": "Employee Benefits",
  "businessArea": "Business Support",
  "businessDomain": "Human Resources",
  "functionalPattern": "Administer",
  "assetType": "Benefit Enrollment",
  "controlRecord": "Benefit Enrollment Administrative Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.employeebenefits",
  "deep": false
 },
 {
  "repo": "sd-workforce-development",
  "serviceDomain": "Workforce Development",
  "businessArea": "Business Support",
  "businessDomain": "Human Resources",
  "functionalPattern": "Develop",
  "assetType": "Workforce Plan",
  "controlRecord": "Workforce Plan Development Project",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.workforcedevelopment",
  "deep": false
 },
 {
  "repo": "sd-building-management",
  "serviceDomain": "Building Management",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Operate",
  "assetType": "Facility",
  "controlRecord": "Facility Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.buildingmanagement",
  "deep": false
 },
 {
  "repo": "sd-corporate-insurance",
  "serviceDomain": "Corporate Insurance",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Administer",
  "assetType": "Insurance Policy",
  "controlRecord": "Insurance Policy Administrative Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.corporateinsurance",
  "deep": false
 },
 {
  "repo": "sd-corporate-relationship",
  "serviceDomain": "Corporate Relationship",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Manage",
  "assetType": "Corporate Relationship",
  "controlRecord": "Corporate Relationship Management Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.corporaterelationship",
  "deep": false
 },
 {
  "repo": "sd-corporate-communications",
  "serviceDomain": "Corporate Communications",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Operate",
  "assetType": "Communication Campaign",
  "controlRecord": "Communication Campaign Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.corporatecommunications",
  "deep": false
 },
 {
  "repo": "sd-procurement",
  "serviceDomain": "Procurement",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Process",
  "assetType": "Purchase Order",
  "controlRecord": "Purchase Order Procedure",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.procurement",
  "deep": false
 },
 {
  "repo": "sd-document-management",
  "serviceDomain": "Document Management",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Maintain",
  "assetType": "Document",
  "controlRecord": "Document Maintenance Agreement",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.documentmanagement",
  "deep": false
 },
 {
  "repo": "sd-archive-services",
  "serviceDomain": "Archive Services",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Maintain",
  "assetType": "Archive Item",
  "controlRecord": "Archive Item Maintenance Agreement",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.archiveservices",
  "deep": false
 },
 {
  "repo": "sd-knowledge-exchange",
  "serviceDomain": "Knowledge Exchange",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Operate",
  "assetType": "Knowledge Article",
  "controlRecord": "Knowledge Article Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.knowledgeexchange",
  "deep": false
 },
 {
  "repo": "sd-legal-services",
  "serviceDomain": "Legal Services",
  "businessArea": "Business Support",
  "businessDomain": "Corporate Services",
  "functionalPattern": "Provide Advice",
  "assetType": "Legal Matter",
  "controlRecord": "Legal Matter Advisory Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.legalservices",
  "deep": false
 },
 {
  "repo": "sd-systems-administration",
  "serviceDomain": "Systems Administration",
  "businessArea": "Business Support",
  "businessDomain": "Technology and Operations",
  "functionalPattern": "Administer",
  "assetType": "System Configuration",
  "controlRecord": "System Configuration Administrative Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.systemsadministration",
  "deep": false
 },
 {
  "repo": "sd-platform-operations",
  "serviceDomain": "Platform Operations",
  "businessArea": "Business Support",
  "businessDomain": "Technology and Operations",
  "functionalPattern": "Operate",
  "assetType": "Platform Service",
  "controlRecord": "Platform Service Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.platformoperations",
  "deep": false
 },
 {
  "repo": "sd-network-operations",
  "serviceDomain": "Network Operations",
  "businessArea": "Business Support",
  "businessDomain": "Technology and Operations",
  "functionalPattern": "Operate",
  "assetType": "Network Service",
  "controlRecord": "Network Service Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.networkoperations",
  "deep": false
 },
 {
  "repo": "sd-software-deployment",
  "serviceDomain": "Software Deployment",
  "businessArea": "Business Support",
  "businessDomain": "Technology and Operations",
  "functionalPattern": "Process",
  "assetType": "Software Release",
  "controlRecord": "Software Release Procedure",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.softwaredeployment",
  "deep": false
 },
 {
  "repo": "sd-it-standards-and-guidelines",
  "serviceDomain": "IT Standards And Guidelines",
  "businessArea": "Business Support",
  "businessDomain": "Technology and Operations",
  "functionalPattern": "Catalog",
  "assetType": "IT Standard",
  "controlRecord": "IT Standard Directory Entry",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.itstandardsandguidelines",
  "deep": false
 },
 {
  "repo": "sd-site-operations",
  "serviceDomain": "Site Operations",
  "businessArea": "Business Support",
  "businessDomain": "Technology and Operations",
  "functionalPattern": "Operate",
  "assetType": "Site Operation",
  "controlRecord": "Site Operation Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.siteoperations",
  "deep": false
 },
 {
  "repo": "sd-service-desk",
  "serviceDomain": "Service Desk",
  "businessArea": "Business Support",
  "businessDomain": "Technology and Operations",
  "functionalPattern": "Operate",
  "assetType": "Service Ticket",
  "controlRecord": "Service Ticket Operating Session",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.servicedesk",
  "deep": false
 },
 {
  "repo": "sd-enterprise-architecture",
  "serviceDomain": "Enterprise Architecture",
  "businessArea": "Business Support",
  "businessDomain": "Business Command and Control",
  "functionalPattern": "Design",
  "assetType": "Architecture Blueprint",
  "controlRecord": "Architecture Blueprint Design",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.enterprisearchitecture",
  "deep": false
 },
 {
  "repo": "sd-business-development",
  "serviceDomain": "Business Development",
  "businessArea": "Business Support",
  "businessDomain": "Business Command and Control",
  "functionalPattern": "Plan",
  "assetType": "Business Development Plan",
  "controlRecord": "Business Development Plan Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.businessdevelopment",
  "deep": false
 },
 {
  "repo": "sd-business-risk-models",
  "serviceDomain": "Business Risk Models",
  "businessArea": "Business Support",
  "businessDomain": "Business Command and Control",
  "functionalPattern": "Develop",
  "assetType": "Business Risk Model",
  "controlRecord": "Business Risk Model Development Project",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.businessriskmodels",
  "deep": false
 },
 {
  "repo": "sd-enterprise-planning",
  "serviceDomain": "Enterprise Planning",
  "businessArea": "Business Support",
  "businessDomain": "Business Command and Control",
  "functionalPattern": "Plan",
  "assetType": "Enterprise Plan",
  "controlRecord": "Enterprise Plan Plan",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.enterpriseplanning",
  "deep": false
 },
 {
  "repo": "sd-corporate-strategy",
  "serviceDomain": "Corporate Strategy",
  "businessArea": "Business Support",
  "businessDomain": "Business Command and Control",
  "functionalPattern": "Direct",
  "assetType": "Strategy Directive",
  "controlRecord": "Strategy Directive Strategy",
  "namespace": "bian-business-support",
  "package": "com.bank.bian.corporatestrategy",
  "deep": false
 }
];
